//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimilarImages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimilarImages.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The algorithm when calculating image hashes. 的本地化字符串。
        /// </summary>
        internal static string AlgorithmHelp {
            get {
                return ResourceManager.GetString("AlgorithmHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Value:  的本地化字符串。
        /// </summary>
        internal static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted 的本地化字符串。
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move this image [ 的本地化字符串。
        /// </summary>
        internal static string DeleteImage_1 {
            get {
                return ResourceManager.GetString("DeleteImage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ] to recycle bin? 的本地化字符串。
        /// </summary>
        internal static string DeleteImage_2 {
            get {
                return ResourceManager.GetString("DeleteImage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag &amp; Drop folder(s) here... 的本地化字符串。
        /// </summary>
        internal static string DragHere {
            get {
                return ResourceManager.GetString("DragHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder does not exist. 的本地化字符串。
        /// </summary>
        internal static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support folder(s) only. 的本地化字符串。
        /// </summary>
        internal static string FolderOnly {
            get {
                return ResourceManager.GetString("FolderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 1 的本地化字符串。
        /// </summary>
        internal static string Image1 {
            get {
                return ResourceManager.GetString("Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 2 的本地化字符串。
        /// </summary>
        internal static string Image2 {
            get {
                return ResourceManager.GetString("Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The interpolation mode when resizing images. 的本地化字符串。
        /// </summary>
        internal static string InterpolationHelp {
            get {
                return ResourceManager.GetString("InterpolationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please drag &amp; drop folder(s) to this form. 的本地化字符串。
        /// </summary>
        internal static string NoFolder {
            get {
                return ResourceManager.GetString("NoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No result 的本地化字符串。
        /// </summary>
        internal static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \nUsage: When sampling, resize images to &quot;Precision * Precision&quot;.\nNotice: Don&apos;t set it too large to run out of memory. 的本地化字符串。
        /// </summary>
        internal static string PresionHelp {
            get {
                return ResourceManager.GetString("PresionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %\nRange: 0-99%.\nUsage: Return results greater than the threshold.\nNotice: Don&apos;t set a low threshold when processing mass images as the operation will take too long. 的本地化字符串。
        /// </summary>
        internal static string ThresholdHelp {
            get {
                return ResourceManager.GetString("ThresholdHelp", resourceCulture);
            }
        }
    }
}
